CREATE TABLE IF NOT EXISTS despesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(200) NOT NULL,
    valor NUMERIC(15,2) NOT NULL,
    data DATE NOT NULL,
    categoria_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_despesas_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id),
    CONSTRAINT fk_despesas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT ck_despesas_valor_positivo CHECK (valor > 0)
);

CREATE INDEX IF NOT EXISTS idx_despesas_usuario_data ON despesas (usuario_id, data);
